# Generated by Django 4.2.4 on 2023-08-12 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_countries_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
