# Generated by Django 4.2.4 on 2023-08-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_twit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
