# Generated by Django 4.2.4 on 2023-08-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
