# Generated by Django 4.2.4 on 2023-08-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.twits')),
            ],
            options={
                'db_table': 'Profiles',
            },
        ),
    ]
