# Generated by Django 4.2.4 on 2023-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
