# Generated by Django 4.2.4 on 2023-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('followers', models.PositiveIntegerField()),
                ('subscriptions', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
