# Generated by Django 4.2.4 on 2023-08-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_account_delete_profiles'),
        ('core', '0019_profile'),
    ]

    operations = [
    ]
