# Generated by Django 4.2.4 on 2023-08-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_0018_account_delete_profiles_0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.users'),
            preserve_default=False,
        ),
    ]
