# Generated by Django 4.2.4 on 2023-08-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_account_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.FileField(null=True, upload_to='profile/photo/'),
        ),
    ]
