# Generated by Django 4.2.4 on 2023-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_account_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.ImageField(null=True, upload_to='profile/photo/'),
        ),
    ]
