# Generated by Django 4.2.4 on 2023-08-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_account_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
