# Generated by Django 4.2.4 on 2023-08-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_account_country_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscriptions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='twit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.twits'),
        ),
    ]
