# Generated by Django 4.2.4 on 2023-08-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_account_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='twit',
        ),
        migrations.AddField(
            model_name='twits',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.account'),
            preserve_default=False,
        ),
    ]
