# Generated by Django 4.2.4 on 2023-08-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_account_twit_twits_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twits',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.account'),
        ),
    ]
