# Generated by Django 4.2.4 on 2023-08-21 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_remove_twits_account_twits_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twits',
            name='user',
        ),
        migrations.AddField(
            model_name='twits',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
