# Generated by Django 4.2.4 on 2023-08-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_twits_account_twits_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
