# Generated by Django 4.2.4 on 2023-08-30 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_comments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twits',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twit', to=settings.AUTH_USER_MODEL),
        ),
    ]
