# Generated by Django 4.2.4 on 2023-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_twits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twits',
            name='tags',
            field=models.ManyToManyField(db_table='twits_tags', related_name='twit', to='core.tags'),
        ),
    ]
