# Generated by Django 4.2.4 on 2023-09-05 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_alter_twits_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='fallowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
