# Generated by Django 4.2.4 on 2023-10-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ManyToManyField(db_table='users_likes', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
