# Generated by Django 4.2.4 on 2023-10-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_likes_created_at_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twits',
            name='like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='twit', to='core.likes'),
            preserve_default=False,
        ),
    ]
