# Generated by Django 4.2.4 on 2023-10-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_twits_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='twit',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.twits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twits',
            name='like',
            field=models.PositiveIntegerField(),
        ),
    ]
