# Generated by Django 4.2.4 on 2023-10-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_twits_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='twits',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
