# Generated by Django 4.2.4 on 2023-10-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_likes_user_likes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
    ]
